version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  db:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
  web:
    restart: always
    build: .
    container_name: web-application
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn Blog.wsgi -b 0.0.0.0:8000 --reload"
    volumes:
      - ./src:/src
      - /static:/static
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    expose:
      - "8000"
    depends_on:
      - db
